export const SET_ROUTER_URL = 'SET_ROUTER_URL';
export const TODO = {
    ADD_TODO: 'ADD_TODO',
    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
    TOGGLE_TODO: 'TOGGLE_TODO',
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE'
};

export const PRODUCT = {
    SET_FILTER_TEXT: "SET_FILTER_TEXT",
    SET_IN_STOCK_ONLY: "SET_IN_STOCK_ONLY",
    SET_PRODUCTS: "SET_PRODUCTS"
}